table dPerformanceCluster

	column 'performance_cluster_key'
		dataType: int64
		sourceColumn: performance_cluster_key
		summarizeBy: none
		isHidden

	column 'cluster_name'
		dataType: string
		sourceColumn: cluster_name
		summarizeBy: none

	partition dPerformanceCluster = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents("C:\Users\lucas\Desktop\Portfolio\HR Analytics\archive (1)\powerbi_en\dPerformanceCluster.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"performance_cluster_key", Int64.Type}, {"cluster_name", type text}}, "en-US")
			in
			    Typed
